//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.lendingtree.services;

import android.app.Activity;
import android.content.Context;
import android.view.View;

public final class HttpRequestClient_
    extends HttpRequestClient
{

    private Context context_;

    private HttpRequestClient_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
        ((CustomResponseErrorHandler_) Errhandler).afterSetContentView_();
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        restClient = new RestClient_();
        Errhandler = CustomResponseErrorHandler_.getInstance_(context_);
    }

    public static HttpRequestClient_ getInstance_(Context context) {
        return new HttpRequestClient_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
